<?php
/**
 * Created by PhpStorm.
 * User: lychee
 * Date: 2018/11/23
 * Time: 15:51
 */

namespace common\widgets\ajaxInput;

use yii\base\InvalidArgumentException;
use yii\base\Widget;


class AjaxInputWidget extends Widget
{
    /**
     * @var string 修改的目标地址
     */
    public $url;

    /**
     * @var integer id
     */
    public $id;

    /**
     * @var string id名称
     */
    public $idName = 'id';

    /**
     * @var string 字段名称
     */
    public $field;

    /**
     * @var array input框的相关设置
     */
    public $options = ['class' => 'form-control'];
    /**
     * @var string 字段值
     */
    public $value;

    public $error = 'fail';

    public $success = 'success';

    public $csrf;

    public function init()
    {
        $fields = ['url', 'field'];

        foreach ($fields as $field) {
            if (empty($this->$field)) {
                throw new InvalidArgumentException("请配置{$field}");
            }
        }

        $this->csrf = \Yii::$app->request->csrfToken;

        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        $this->options['class']       .= ' ajax-input';
        $this->options['data-idName']  = $this->idName;
        $this->options['data-field']   = $this->field;
        $this->options['data-success'] = $this->success;
        $this->options['data-error']   = $this->error;
        $this->options['data-csrf']    = $this->csrf;
        $this->options['data-link']    = $this->url;

        return $this->render('index', [
            'value' => $this->value,
            'options' => $this->options,
        ]);
    }
}