<?php
/**
 * Created by PhpStorm.
 * User: lychee
 * Date: 2018/1/6
 * Time: 23:56
 */

namespace common\widgets;

use yii\base\Widget;

class Datepicker extends Widget
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub

        return 111;
    }
}