<?php
/**
 * Created by PhpStorm.
 * User: lychee
 * Date: 2018/6/7
 * Time: 14:39
 */

namespace common\widgets\lang;


use yii\base\Widget;

class LangWidget extends Widget
{
    public $country;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        return $this->render('index');
    }
}