<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Active processes:' => '活动的进程',
    'All dumps successfully removed.' => '所有转储都已成功删除',
    'Are you sure?' => '确定进行该项操作吗？',
    'Create dump' => '创建一个备份',
    'Create time' => '创建时间',
    'Custom dump preset' => '自定义备份预设',
    'Custom restore preset' => '自定义备份恢复',
    'DB manager' => '数据库管理器',
    'Database' => '数据库',
    'Delete' => '删除',
    'Delete all' => '删除全部',
    'Delete from storage' => '从存储中删除',
    'Download' => '下载',
    'Dump deleted from storage.' => '从存储中删除备份',
    'Dump deleted successfully.' => '备份删除成功',
    'Dump failed.' => '备份失败',
    'Dump only schema' => '只备份数据结构',
    'Dump request invalid.' => '备份请求无效',
    'Dump successfully created.' => '成功创建',
    'Dump successfully restored.' => '成功创建备份',
    'Dump uploaded to storage.' => '上传备份到存储',
    'Error deleting dump.' => '删除备份失败',
    'Error deleting dumps.' => '删除备份失败',
    'Name' => '名称',
    'Process complete!' => '进程完成!',
    'Process running with pid={pid}' => '进程的pid是{pid}',
    'Restore' => '恢复备份',
    'Restore failed.' => '恢复备份失败',
    'Run in background' => '后台运行',
    'Size' => '文件大小',
    'Type' => '类型',
    'Upload from storage' => '从存储系统中上传',
    'gzip' => 'gzip压缩',
];
