<?php
/**
 * Created by PhpStorm.
 * User: lychee
 * Date: 2018/6/9
 * Time: 17:13
 */

namespace common\widgets\country;

use yii\base\Widget;

class CountryWidget extends Widget
{
    public $label = '国家';
    public $colClass = 'col-md-6';


    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        return $this->render('index', [
            'colClass' => $this->colClass,
            'label' => $this->label
        ]);
    }
}