<?php
/**
 * Created by PhpStorm.
 * User: lychee
 * Date: 2018/4/22
 * Time: 12:14
 */

namespace api\controllers;


use common\models\VodList;
use yii\data\ActiveDataProvider;
use yii\rest\ActiveController;

class VodController extends ActiveController
{

    public $modelClass = 'common\models\Vod';
    

    public function actions()
    {
        $actions = parent::actions(); // TODO: Change the autogenerated stub
        unset($actions['index']);
        return $actions;
    }

    public function actionIndex()
    {
        $request =  \Yii::$app->request;
        $cid = $request->get('cid');
        $per_page = $request->get('per_page', 12);
        $modelClass = $this->modelClass;

        $dataProvider = new ActiveDataProvider([
            'query' => $cid ? $modelClass::find()->where(['vod_cid' => $cid]) : $modelClass::find(),
            'pagination' => [
                'pageSize' => $per_page,
            ],
        ]);

        return $dataProvider;
    }
}