<?php

namespace backend\models;

use common\models\Vodlink;
use Yii;

/**
 * This is the model class for table "iptv_play_group".
 *
 * @property int $id
 * @property int $vod_id
 * @property string $group_name
 * @property int $sort
 */
class PlayGroup extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'iptv_play_group';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['vod_id', 'sort'], 'integer'],
            [['group_name'], 'string', 'max' => 32],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'vod_id' => 'Vod ID',
            'group_name' => 'Group Name',
            'sort' => 'Sort',
        ];
    }

    /**
     * 获取链接
     */
    public function getLinks()
    {
        return $this->hasMany(Vodlink::className(), [
            'group_id' => 'id'
        ]);
    }

    public function beforeDelete()
    {
        parent::beforeDelete(); // TODO: Change the autogenerated stub
        // 查找所有的子链接 删除
        Vodlink::deleteAll(['group_id' => $this->id]);
    }

}
